### ISSUE TITLE
Filtering argsValue for nominate call

### ISSUE THREAD

**Issue by d4rk0snet** [capsule-corp-ternoa/ternoa-subql#109]
Hello,

Do you have any idea how to filter this : 
          "argsValue": [
            "[5Dc6uTzgiFrMWv6Sn14uvWKKSf8dBUeLca1HZEKXQWPRyyDJ, 5EeeRBQSzx5mmtT5EjPmfEj21GbNRAGy71Q1Q3UTYSuk5Gy4]"
          ],

I tried contains, in , ... nothing works.

What i would like to achive is to check if "5EeeRBQSzx5mmtT5EjPmfEj21GbNRAGy71Q1Q3UTYSuk5Gy4" is in this array.

Thank u for your help !

**Comment by ipapandinas** [comment]
hi,

You must use `contains`, here is an example:

```
{
  extrinsics(
    filter: {
      module: { equalTo: "balances" }
      call: { equalTo: "transfer" }
      argsValue: {
            contains: "5EeeRBQSzx5mmtT5EjPmfEj21GbNRAGy71Q1Q3UTYSuk5Gy4"
          }
    }
  ) {
    totalCount,
    nodes {
      argsValue
      extrinsicIndex
      timestamp
      nonce
      id
      blockId
      module
      call
      signer
      success
    }
  }
}
```

**Comment by d4rk0snet** [comment]
Hi,

No i'm sorry , it can't work since, it's a string under argValues and i think it should be an array.
I checked on other calls, and it was an array and indeed contains worked in these cases.

What do you think about it ?

**Comment by ipapandinas** [comment]
Can you provide the full query please ?

**Comment by d4rk0snet** [comment]
Hi @ipapandinas,

{
  extrinsics(
    orderBy: [BLOCK_HEIGHT_DESC]
    filter: {
      and: [
        { 
          call: {equalTo: "nominate"}
            signer: { equalTo: "5EHtVs3YZSEWht4MiKqFFH8ipVGFrLoE9U3mHMFU3nHLMBJE"}
          argsValue: { contains : "5EeeRBQSzx5mmtT5EjPmfEj21GbNRAGy71Q1Q3UTYSuk5Gy4"}

        }
       ]
    }
  )
  {nodes { argsValue signer block {timestamp}}}
}

**Comment by ipapandinas** [comment]
This filtering level would not be possible using GraphQL since the substrate `nominate` extrinsic returns a stringified array as first element of `argsValue`.
I suggest you to implement this filtering on the application side by parsing `argsValue[0]`.

**Comment by ipapandinas** [comment]
I am closing this issue which concerns the [dictionary](https://github.com/capsule-corp-ternoa/ternoa-subql-dictionary)
