### ISSUE TITLE
refactor code consistency

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-subql#112]
Some cleanings have to be done to improve code consistency:

- [ ] rename _nftTransfer.ts_ into _nftOperations.ts_
- [ ] create an enum for nft operations
- [ ] remove comments (MarketplaceDataType in marketplace handlers)
- [ ] remove DepositMade from mapping

**Comment by AntonioliBenjamin** [comment]
I can clean it 😊

**Comment by ipapandinas** [comment]
Hi @AntonioliBenjamin 🙋‍♂️

**Comment by AntonioliBenjamin** [comment]
hi @ipapandinas 
sorry for the inconvenience, as you can see I'm still bad with git.
I tried pushing on the "dev" branch with the command `git push origin dev`
I don't have permission to push `remote: Permission to capsule-corp-ternoa/ternoa-subql.git denied to AntonioliBenjamin.`

I'm sorry, I'm in misunderstanding

**Comment by ipapandinas** [comment]
Thank you for your first contribution @AntonioliBenjamin 🏆
Code will be deploy in early November!

**Comment by AntonioliBenjamin** [comment]
@ipapandinas 
a pleasure to contribute at my humble level in this project that I particularly like.
I am still a student and I hope to be able to contribute again during my skills development !
