### ISSUE TITLE
Rental NFTs Indexer - Rentee/Renter Cancellation Fee

### ISSUE THREAD

**Issue by kamccy** [capsule-corp-ternoa/ternoa-subql#127]
Added a rentee and renter cancellation fee of 200000 CAPS for NFT: "id": "51541" 
In the indexer the cancellation fee is showing up as:

- "renteeCancellationFee": "0",
-  "renteeCancellationFeeRounded": 0,
- "renterCancellationFee": "0",
- "renterCancellationFeeRounded": 0

**Comment by ipapandinas** [comment]
Extrinsic: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Falphanet.ternoa.com#/explorer/query/0x7adc8d02e20dbd9588bdb68990a115d4ee6987fc80f6c158b04ed09d0b762776

**Comment by Victor-Salomon** [comment]
@kamccy it's solved. Thank you !
