### ISSUE TITLE
[Rent] Error on contract creation

### ISSUE THREAD

**Issue by Leouarz** [capsule-corp-ternoa/ternoa-subql#130]
![image](https://user-images.githubusercontent.com/15839293/202709766-e53a023b-7cd0-4b62-a0cf-e9b6b077cc46.png)
![image](https://user-images.githubusercontent.com/15839293/202709846-fa7b09f3-7c76-445d-9371-5fb4e108a1f2.png)
![image](https://user-images.githubusercontent.com/15839293/202710052-a3afe685-6afd-49ee-ae85-c696e5721381.png)

Issue + typo : 
![image](https://user-images.githubusercontent.com/15839293/202710297-12ed2e5c-3dc6-4301-80f0-2b1d02ae145e.png)
Here, line 70, should be : 
```javascript
record.rentFeeType = RentFeeAction.NFT
```

**Comment by ipapandinas** [comment]
Fixed here 👉 https://github.com/capsule-corp-ternoa/ternoa-subql/commit/7b6c53b5c5a0f55d5df37fb7ac1b5410dbf48401

**Comment by ipapandinas** [comment]
but not with the correct enum `RentFeeAction`, I let the issue open to fix it properly
