### ISSUE TITLE
Collection : Limit appears on chain but not on indexer

### ISSUE THREAD

**Issue by Leouarz** [capsule-corp-ternoa/ternoa-subql#149]
For collection ID 183 : 
![image](https://user-images.githubusercontent.com/15839293/206892588-615fd6ed-6d44-4c0c-a387-6115ba737594.png)

On indexer : 
![image](https://user-images.githubusercontent.com/15839293/206892601-e2875085-9412-4aaa-8344-ebed094712fd.png)

**Comment by Victor-Salomon** [comment]
Collection created a block id : 3482307
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmainnet.ternoa.network#/explorer/query/0xb8229823f0b0ab935d69f7e95e7abc1cc635c17ad76a0ff2cea086192090e8c6

First nft added at block : 3482701

**Comment by Victor-Salomon** [comment]
fixed in commit : 99bd11979ad1c3b6900649337a449d95b72cf1bf
