### ISSUE TITLE
NFT Buy - Bug on indexer

### ISSUE THREAD

**Issue by Leouarz** [capsule-corp-ternoa/ternoa-subql#157]
There is a bug on indexer where it actually passed a block or skipped the NFT Buy event on the mainnet.
Seems kinda weird cause we should have seen this issue sooner.

Currently the indexer has passed the block where a buy transaction happened. Yet the NFT is still considered on sale.

Block where transaction happened : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmainnet.ternoa.network#/explorer/query/3982312

Chain data : 
![image](https://user-images.githubusercontent.com/15839293/212487129-fb4c0a08-17b9-4ac4-be94-c1783fd02db9.png)

Indexer data : 
![image](https://user-images.githubusercontent.com/15839293/212487132-cb05495f-a79c-4ecc-a38b-909a5c989900.png)

**Comment by Victor-Salomon** [comment]
Mp creation block: 1232305
Collection creation block: 2100052
NFT creation block: 2111186
NFT Listing block: 3893222
NFT Sold block: 3982312

**Comment by Leouarz** [comment]
Noice, let's just take the event manually on indexer

**Comment by ipapandinas** [comment]
We spotted 2 additional issues on Auctions & Marketplace, we will reindex from scratch
