### ISSUE TITLE
Indexer out of sync

### ISSUE THREAD

**Issue by Leouarz** [capsule-corp-ternoa/ternoa-subql#184]
Hello, the indexer is kinda out of sync and has missed to basic event. 
Eg: 
 on graphQL
```
{
  nftEntities(
    first: 100
    filter: {nftId: {equalTo: "359381"}}
  ) {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
    }
    nodes {
      nftId
      creator
      owner
      isListed
    }
  }
}
```

![image](https://github.com/capsule-corp-ternoa/ternoa-subql/assets/15839293/0a61f1af-125a-4ec1-99b3-32e5a80034c3)

And on chain : 
![image](https://github.com/capsule-corp-ternoa/ternoa-subql/assets/15839293/ca4bbc5f-af43-4edb-b76a-de4a0bc99f5b)

**Comment by Victor-Salomon** [comment]
Hey @Leouarz 
It should be fixed.
<img width="1547" alt="image" src="https://github.com/capsule-corp-ternoa/ternoa-subql/assets/68683271/a4638db0-b829-4d5e-82b4-57cb9daeec47">

Thanks for the backup ⚡️
